import type { Metadata } from "next";
import {Geist, Geist_Mono, Inter} from "next/font/google";
import "./globals.css";
import {Navbar} from "@/components/layout/navbar";
import {Footer} from "@/components/layout/footer";
import {cn} from "@/lib/utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const inter = Inter({ subsets: ["latin"] })
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" suppressHydrationWarning>
      <body
          className={cn(
              inter.className,
              "min-h-screen bg-background text-foreground antialiased"
          )}
      >
      <div className="relative flex min-h-screen flex-col">
          <Navbar />

          <main className="flex-1">
              {children}
          </main>

          <Footer />
      </div>
      </body>
      </html>
  );
}
